In [1]:
!nvidia-smi

Sun Apr 27 14:27:15 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A100-SXM4-40GB          Off |   00000000:00:04.0 Off |                    0 |
| N/A   33C    P0             47W /  400W |       0MiB /  40960MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+-----

In [2]:
import os
os.environ["CUDA_LAUNCH_BLOCKING"] = "1"


In [3]:
# ================================================================
# Step 1: Install Dependencies (No Gradio)
# ================================================================
print("Uninstalling potentially conflicting numpy/scipy...")
!pip uninstall -y numpy scipy

print("\nReinstalling numpy and scipy first...")
!pip install -q numpy scipy

print("\nUpgrading pip and installing TTS...")
!pip install -q --upgrade pip
# Use --no-cache-dir to ensure fresh downloads if needed
!pip install -q --no-cache-dir TTS # Gradio removed
print("Installation Complete.")

# --- Verification (Optional but recommended) ---
print("\nVerifying NumPy version after installation:")
!python -c "import numpy; print(numpy.__version__)"
print("Verifying SciPy version after installation:")
!python -c "import scipy; print(scipy.__version__)"

Uninstalling potentially conflicting numpy/scipy...
Found existing installation: numpy 2.0.2
Uninstalling numpy-2.0.2:
  Successfully uninstalled numpy-2.0.2
Found existing installation: scipy 1.14.1
Uninstalling scipy-1.14.1:
  Successfully uninstalled scipy-1.14.1

Reinstalling numpy and scipy first...
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 1.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 3.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.4/16.4 MB 107.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 37.6/37.6 MB 59.0 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.2.5 which is incompatible.
tensorflow 2.18.0 requires numpy<2.1.0,>=1.26.0, but you have numpy 2.2.5 which is incompatible.

Upgrading pip 

In [4]:
!pip install requests flask flask_cors uuid ngrok

  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 48.8 MB/s eta 0:00:00
  DEPRECATION: Building 'uuid' using the legacy setup.py bdist_wheel mechanism, which will be removed in a future version. pip 25.3 will enforce this behaviour change. A possible replacement is to use the standardized build interface by setting the `--use-pep517` option, (possibly combined with `--no-build-isolation`), or adding a `pyproject.toml` file to the source tree of 'uuid'. Discussion can be found at https://github.com/pypa/pip/issues/6334
  Created wheel for uuid: filename=uuid-1.30-py3-none-any.whl size=6477 sha256=3196559f588a5877088f8567c75b278109c7487d27afaa74620823f83cde714f
  Stored in directory: /root/.cache/pip/wheels/e0/01/df/bd20df409bd81f8b99e6cd343c5f49731dc0a20eefefdafae0
Successfully built uuid
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3/3 [flask_cors]


In [1]:
!pip install llama-index
!pip install llama-index-embeddings-huggingface
!pip install auto-gptq
!pip install optimum
!pip install bitsandbytes
!pip install faiss-cpu transformers


  Using cached optimum-1.24.0-py3-none-any.whl.metadata (21 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.1/76.1 MB 112.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 30.7/30.7 MB 123.8 MB/s eta 0:00:00


In [ ]:
!python --version

Python 3.11.12


In [2]:
from llama_index.embeddings.huggingface import HuggingFaceEmbedding
from llama_index.core import Settings, SimpleDirectoryReader, VectorStoreIndex,Document
from llama_index.core.retrievers import VectorIndexRetriever
from llama_index.core.query_engine import RetrieverQueryEngine
from llama_index.core.postprocessor import SimilarityPostprocessor

# import any embedding model on HF hub (https://huggingface.co/spaces/mteb/leaderboard)
Settings.embed_model = HuggingFaceEmbedding(model_name="BAAI/bge-small-en-v1.5")
# Settings.embed_model = HuggingFaceEmbedding(
#     model_name="BAAI/bge-small-en-v1.5",
#     device="cpu"  # 👈 this avoids GPU
# )
# Settings.embed_model = HuggingFaceEmbedding(model_name="thenlper/gte-large") # alternative model
# Settings.embed_model = HuggingFaceEmbedding(
#     # model_name="thenlper/gte-large",
#     # device="cuda"  # switch back to GPU
# )

Settings.llm = None
Settings.chunk_size = 384
Settings.chunk_overlap = 25

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/94.8k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/743 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/133M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/366 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/711k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

LLM is explicitly disabled. Using MockLLM.


In [3]:
# ================================================================
# Step 2: Import Libraries and Load the XTTS Model (with PyTorch Fix)
# ================================================================
print("\nImporting libraries and loading model...")
import os
import time
import torch

# --- PyTorch >= 2.6 Safe Loading Fix ---
import torch.serialization
try:
    from TTS.tts.configs.xtts_config import XttsConfig
    from TTS.tts.models.xtts import XttsAudioConfig
    from TTS.config.shared_configs import BaseDatasetConfig
    from TTS.tts.models.xtts import XttsArgs
    safe_globals_list = [XttsConfig, XttsAudioConfig, BaseDatasetConfig, XttsArgs]
    torch.serialization.add_safe_globals(safe_globals_list)
    print(f"Attempted to add {len(safe_globals_list)} classes to safe globals for PyTorch loading.")
except ImportError as ie:
    print(f"Warning: Could not import one or more required TTS classes: {ie}. Loading might fail.")
except AttributeError:
    print("Warning: torch.serialization or add_safe_globals not found (PyTorch version issue?). Loading might fail.")
# --- End PyTorch Fix ---

from TTS.api import TTS
from IPython.display import Audio, display

# Check for GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
if device == "cpu":
    print("WARNING: CUDA not available, running on CPU. This will be VERY SLOW.")
else:
    print(f"PyTorch version: {torch.__version__}")
    print(f"Using device: {device}")

# --- Load the TTS Model ---
audio_model_name = "tts_models/multilingual/multi-dataset/xtts_v2"
print(f"\nLoading XTTS model: {audio_model_name}")
print("This might take several minutes for the first download...")

load_start_time = time.time()
tts_model = None # Initialize tts_model
try:
    tts_model = TTS(audio_model_name).to(device)
    load_end_time = time.time()
    print(f"Model loaded successfully in {load_end_time - load_start_time:.2f} seconds.")
except Exception as e:
    print(f"\n--- FATAL ERROR LOADING MODEL ---")
    print(f"{e}")
    print("Cannot proceed without a loaded model. Please check previous errors, restart runtime, and try again.")
    # Optional: raise e


Importing libraries and loading model...
Attempted to add 4 classes to safe globals for PyTorch loading.
PyTorch version: 2.6.0+cu124
Using device: cuda

Loading XTTS model: tts_models/multilingual/multi-dataset/xtts_v2
This might take several minutes for the first download...
 > You must confirm the following:
 | > "I have purchased a commercial license from Coqui: licensing@coqui.ai"
 | > "Otherwise, I agree to the terms of the non-commercial CPML: https://coqui.ai/cpml" - [y/n]
 | | > y
 > Downloading model to /root/.local/share/tts/tts_models--multilingual--multi-dataset--xtts_v2


100%|█████████▉| 1.86G/1.87G [00:21<00:00, 103MiB/s]
100%|██████████| 1.87G/1.87G [00:21<00:00, 86.2MiB/s]
100%|██████████| 4.37k/4.37k [00:00<00:00, 13.9kiB/s]

100%|██████████| 361k/361k [00:00<00:00, 978kiB/s]
100%|██████████| 32.0/32.0 [00:00<00:00, 89.1iB/s]
 44%|████▎     | 3.38M/7.75M [00:00<00:00, 33.8MiB/s]

 > Model's license - CPML
 > Check https://coqui.ai/cpml.txt for more info.
 > Using model: xtts


100%|██████████| 7.75M/7.75M [00:15<00:00, 33.8MiB/s]GPT2InferenceModel has generative capabilities, as `prepare_inputs_for_generation` is explicitly overwritten. However, it doesn't directly inherit from `GenerationMixin`. From 👉v4.50👈 onwards, `PreTrainedModel` will NOT inherit from `GenerationMixin`, and this model will lose the ability to call `generate` and other related functions.
  - If you're using `trust_remote_code=True`, you can get rid of this warning by loading the model with an auto class. See https://huggingface.co/docs/transformers/en/model_doc/auto#auto-classes
  - If you are the owner of the model architecture code, please modify your model class such that it inherits from `GenerationMixin` (after `PreTrainedModel`, otherwise you'll get an exception).
  - If you are not the owner of the model architecture class, please contact the model code owner to update it.


Model loaded successfully in 44.87 seconds.


In [4]:
from transformers import AutoModelForCausalLM, AutoTokenizer

# Specify the base model name
text_model_name = "TheBloke/Mistral-7B-Instruct-v0.2-GPTQ"

# Load the base model
text_model = AutoModelForCausalLM.from_pretrained(text_model_name,
                                             device_map="auto",
                                             trust_remote_code=False,
                                             revision="main")

# Load the tokenizer
tokenizer = AutoTokenizer.from_pretrained(text_model_name, use_fast=True)

# Set the padding token to be the same as the eos_token
tokenizer.pad_token = tokenizer.eos_token


config.json:   0%|          | 0.00/1.08k [00:00<?, ?B/s]

/usr/local/lib/python3.11/dist-packages/auto_gptq/nn_modules/triton_utils/kernels.py:410: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @custom_fwd
/usr/local/lib/python3.11/dist-packages/auto_gptq/nn_modules/triton_utils/kernels.py:418: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  @custom_bwd
/usr/local/lib/python3.11/dist-packages/auto_gptq/nn_modules/triton_utils/kernels.py:461: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @custom_fwd(cast_inputs=torch.float16)
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`


model.safetensors:   0%|          | 0.00/4.16G [00:00<?, ?B/s]

`loss_type=None` was set in the config but it is unrecognised.Using the default loss: `ForCausalLMLoss`.
Some weights of the model checkpoint at TheBloke/Mistral-7B-Instruct-v0.2-GPTQ were not used when initializing MistralForCausalLM: ['model.layers.0.mlp.down_proj.bias', 'model.layers.0.mlp.gate_proj.bias', 'model.layers.0.mlp.up_proj.bias', 'model.layers.0.self_attn.k_proj.bias', 'model.layers.0.self_attn.o_proj.bias', 'model.layers.0.self_attn.q_proj.bias', 'model.layers.0.self_attn.v_proj.bias', 'model.layers.1.mlp.down_proj.bias', 'model.layers.1.mlp.gate_proj.bias', 'model.layers.1.mlp.up_proj.bias', 'model.layers.1.self_attn.k_proj.bias', 'model.layers.1.self_attn.o_proj.bias', 'model.layers.1.self_attn.q_proj.bias', 'model.layers.1.self_attn.v_proj.bias', 'model.layers.10.mlp.down_proj.bias', 'model.layers.10.mlp.gate_proj.bias', 'model.layers.10.mlp.up_proj.bias', 'model.layers.10.self_attn.k_proj.bias', 'model.layers.10.self_attn.o_proj.bias', 'model.layers.10.self_attn.q_pr

generation_config.json:   0%|          | 0.00/111 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/1.46k [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`


tokenizer.model:   0%|          | 0.00/493k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.80M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/72.0 [00:00<?, ?B/s]

In [5]:
# ================================================================
# Step 3: Define the Voice Cloning Function
# ================================================================
import time
def clone_voice(reference_audio_path, text_to_speak, language="en", output_path="cloned_speech.wav"):
    """
    Uses the pre-loaded tts_model to generate speech directly.

    Args:
        reference_audio_path (str): Path to the input reference audio file.
        text_to_speak (str): The text to be synthesized.
        language (str, optional): Language code for synthesis. Defaults to "en".
        output_path (str, optional): Path to save the generated WAV file. Defaults to "cloned_speech.wav".

    Returns:
        str: The path to the generated audio file if successful, None otherwise.
    """
    global tts_model # Access the globally loaded model


    if tts_model is None:
        print("ERROR: TTS Model not loaded. Please ensure Step 2 ran successfully.")
        return None
    if not os.path.exists(reference_audio_path):
        print(f"ERROR: Reference audio not found at: {reference_audio_path}")
        return None
    if not text_to_speak or not isinstance(text_to_speak, str) or text_to_speak.strip() == "":
         print("ERROR: Invalid text provided. Please provide a non-empty string.")
         return None

    print("\n--- Starting Voice Cloning ---")
    print(f" > Reference: {reference_audio_path}")
    print(f" > Text: \"{text_to_speak[:100]}...\"") # Log snippet
    print(f" > Language: {language}")
    print(f" > Output: {output_path}")

    gen_start_time = time.time()
    try:
        tts_model.tts_to_file(
            text=text_to_speak,
            speaker_wav=reference_audio_path,
            language=language,
            file_path=output_path
        )
        gen_end_time = time.time()
        generation_time = gen_end_time - gen_start_time

        if os.path.exists(output_path):
            print(f"\nSuccess! Generated in {generation_time:.2f} seconds.")
            return output_path
        else:
            print("ERROR: TTS generation finished but output file not found.")
            return None

    except RuntimeError as e:
        print(f"\nRUNTIME ERROR during generation: {e}")
        if "CUDA out of memory" in str(e):
            print("--> Try using shorter text or restarting the Colab runtime to free GPU memory.")
        return None
    except Exception as e:
        print(f"\nUNEXPECTED ERROR during generation: {e}")
        return None


In [6]:
!pip install -q gradio PyMuPDF

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.0/54.0 MB 46.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.0/20.0 MB 146.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.5/11.5 MB 150.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15/15 [gradio]


In [ ]:
import gradio as gr
import fitz  # PyMuPDF
from PIL import Image
import shutil
import os
import concurrent.futures
import re
import requests
import time
from pydub import AudioSegment
query_engine_global = None  # Global variable to store the query engine


# Global variable to store instruction
instruction_text = ""


def handle_upload(doc_path, audio_path, image_path,instruction_input):

    global instruction_text
    instruction_text = instruction_input  # Store instruction globally

    doc_text = ""
    saved_doc_path, saved_audio_path, saved_image_path = None, None, None

    upload_dir = "/content/uploaded"
    os.makedirs(upload_dir, exist_ok=True)


    # Clean up existing files
    for f in os.listdir(upload_dir):
        file_path = os.path.join(upload_dir, f)
        if os.path.isfile(file_path):
            os.remove(file_path)



    if doc_path:
          doc_ext = os.path.splitext(doc_path)[1]  # Get file extension
          saved_doc_path = os.path.join(upload_dir, f"uploaded_document{doc_ext}")
          shutil.copy(doc_path, saved_doc_path)  # Save the uploaded document

          if doc_ext == ".pdf":
              # Read the PDF and convert to text
              doc = fitz.open(saved_doc_path)
              doc_text = ""  # Initialize empty string to store text
              for page in doc:
                  doc_text += page.get_text()  # Extract text from each page
              doc.close()

              # Save the extracted text into a .txt file
              text_doc_path = os.path.join(upload_dir, "uploaded_document.txt")
              with open(text_doc_path, 'w', encoding='utf-8') as f:
                  f.write(doc_text)  # Write the extracted text into the .txt file

              # Set the new document path to the text document
              saved_doc_path = text_doc_path  # Use the text document for uploading

          else:
              # If the document is already a text file (or non-PDF), just read it
              with open(saved_doc_path, 'r', encoding='utf-8', errors='ignore') as f:
                  doc_text = f.read()

    if audio_path:
        audio = AudioSegment.from_file(audio_path)
        saved_audio_path = os.path.join(upload_dir, "uploaded_audio.wav")
        audio.export(saved_audio_path, format="wav")

    if image_path:
        image = Image.open(image_path).convert("RGB")  # Convert to RGB to ensure PNG compatibility
        saved_image_path = os.path.join(upload_dir, "uploaded_image.png")
        image.save(saved_image_path, format="PNG")

    return doc_text[:1000], saved_audio_path, saved_image_path, instruction_input


def create_clone_with_timeout(doc_text, audio_path, image_path, timeout_duration=300):
    def task():
        return create_clone(doc_text, audio_path, image_path)

    with concurrent.futures.ThreadPoolExecutor(max_workers=1) as executor:
        future = executor.submit(task)

        try:
            result = future.result(timeout=timeout_duration)
            return "✅ Clone created successfully!"
        except concurrent.futures.TimeoutError:
            print("⏰ Clone creation timed out after", timeout_duration, "seconds")
            return "❌ Clone creation timed out. Please try again with smaller files or simpler queries."


def create_clone(doc_text, audio_path, image_path):
    global query_engine_global

    try:
        print("🚀 Starting clone creation...")
        print(f"📝 Text preview:\n{doc_text[:500]}")
        print(f"🔊 Audio path: {audio_path}")
        print(f"🖼️ Image path: {image_path}")

        documents_dir = "/content/uploaded"
        txt_files = [f for f in os.listdir(documents_dir) if f.endswith('.txt')]

        documents = SimpleDirectoryReader(
            input_files=[os.path.join(documents_dir, f) for f in txt_files]
        ).load_data(show_progress=True)

        index = VectorStoreIndex.from_documents(documents)

        retriever = VectorIndexRetriever(index=index, similarity_top_k=5)
        query_engine = RetrieverQueryEngine(
            retriever=retriever,
            node_postprocessors=[SimilarityPostprocessor(similarity_cutoff=0.5)],
        )

        query_engine_global = query_engine
        print("✅ Clone created!")
        return "✅ Clone created!"

    except Exception as e:
        print("❌ Error during clone creation:", str(e))
        return f"❌ Error occurred: {str(e)}"


def ask_clone_with_timeout(query, timeout_duration=1000):
    def task():
        return ask_clone(query)

    with concurrent.futures.ThreadPoolExecutor(max_workers=1) as executor:
        future = executor.submit(task)
        try:
            return future.result(timeout=timeout_duration)
        except concurrent.futures.TimeoutError:
            return "❌ Response timed out. Please try again with a shorter question or less load."


def ask_clone(query):
    # import time
    # from IPython.display import Video, display
    global query_engine_global

    if query_engine_global is None:
        return gr.update(visible=False), "⚠️ Please create a clone first."

    try:
        # 🔄 Delete old output.mp4 if it exists
        output_video_path = "/content/output_video.mp4"
        if os.path.exists(output_video_path):
            try:
                os.remove(output_video_path)
                print("🗑️ Old output.mp4 deleted.")
            except Exception as e:
                print(f"⚠️ Failed to delete old output.mp4: {e}")

        # =============================
        # Step 1: Get LLM Answer
        # =============================
        response = query_engine_global.query(query)
        context = "Context:\n"
        # for i in range(5):
        #     context += response.source_nodes[i].text + "\n\n"

        for node in response.source_nodes[:5]:  # Only takes up to 5, no error
            context += node.text + "\n\n"

        comment = query


        prompt_template_w_context = lambda context, comment: f"""{instruction_text}

        {context}
        Please respond to the following comment as that person in only 100 words. Use the context above to answer as first person and say you don't have any answer if relevant information is not available in context and answer as first person necessarily.

        {comment}
        [/INST]"""



        prompt = f"{prompt_template_w_context(context, comment)}\nResponse:"

        inputs = tokenizer(prompt, return_tensors="pt")
        # Tokenize the input
        # inputs = tokenizer(prompt, return_tensors="pt", padding=True, truncation=True, max_length=1024)
        # outputs = text_model.generate(
        #     input_ids=inputs["input_ids"].to("cuda"),
        #     max_new_tokens=200,
        #     eos_token_id=tokenizer.eos_token_id
        # )
        # generated_text = tokenizer.decode(outputs[0], skip_special_tokens=True)

        # Use torch.no_grad() to disable gradient calculations
        with torch.no_grad():
            # Move input tensors to GPU (if available)
            input_ids = inputs["input_ids"].to("cuda")

            # Generate text
            # outputs = text_model.generate(
            #     input_ids=input_ids,
            #     max_new_tokens=150,  # Reduce max tokens to speed up inference
            #     eos_token_id=tokenizer.eos_token_id,
            #     num_return_sequences=1,  # You can adjust this if you want multiple responses
            # )
            outputs = text_model.generate(
                  input_ids=input_ids,
                  max_new_tokens=150,  # Allowing more tokens for better response completeness
                  eos_token_id=tokenizer.eos_token_id,  # Ensuring proper stop token handling
                  num_return_sequences=1,
                  temperature=0.7,  # Control creativity, avoid randomness in abrupt endings
                  top_p=0.9,  # Nucleus sampling for smoother responses
                  pad_token_id=tokenizer.eos_token_id  # Use eos token if padding is needed
              )


            # Decode generated text
            generated_text = tokenizer.decode(outputs[0], skip_special_tokens=True)

        match = re.search(r"Response:\s*(.*?)(?:\n*\(Note:.*|$)", generated_text, re.DOTALL)
        answer = match.group(1).strip() if match else generated_text.strip()

        print("Response:",answer)
        # =============================
        # Step 2: Clone Voice to Shared Path
        # =============================
        shared_dir = "/content/generated"
        os.makedirs(shared_dir, exist_ok=True)

        reference_audio_path = "/content/uploaded/uploaded_audio.wav"
        generated_audio_path = os.path.join(shared_dir, "speech.wav")

        if tts_model is not None:
            generated_file_path = clone_voice(
                reference_audio_path=reference_audio_path,
                text_to_speak=answer,
                language="en",
                output_path=generated_audio_path
            )

            if generated_file_path and os.path.exists(generated_file_path):
                print(f"✅ Cloned speech saved to {generated_file_path}")
            else:
                print("❌ Failed to generate speech.")
                return "❌ Failed to generate speech."
        else:
            print("❌ TTS model not loaded.")
            return "❌ TTS model not loaded."

        # Your actual ngrok URL from Colab
        API_URL = "https://d9f2-34-27-183-70.ngrok-free.app"

        # Local paths to your files
        image_path = "/content/uploaded/uploaded_image.png"
        audio_path = "/content/generated/speech.wav"

        # Headers for ngrok
        headers = {"ngrok-skip-browser-warning": "true"}

        # Upload files and start processing
        with open(image_path, 'rb') as img, open(audio_path, 'rb') as aud:
            response = requests.post(
                f"{API_URL}/generate",
                files={'image': img, 'audio': aud},
                headers=headers
            )

        job_id = response.json()['job_id']
        print(f"Job started with ID: {job_id}")

        # Check status until complete
        while True:
            status = requests.get(f"{API_URL}/status/{job_id}", headers=headers).json()
            print(f"Status: {status['status']}")

            if status['status'] == 'completed':
                # Download the video
                print("Downloading video...")
                video = requests.get(f"{API_URL}/download/{job_id}", headers=headers, stream=True)
                with open("output_video.mp4", 'wb') as f:
                    for chunk in video.iter_content(chunk_size=8192):
                        f.write(chunk)
                print("Video downloaded as output_video.mp4")
                break
            elif status['status'] == 'failed':
                print(f"Failed: {status.get('error', 'Unknown error')}")
                break

            time.sleep(5)  # Wait 5 seconds before checking again

        # Create a new unique temp path
        timestamp = int(time.time())
        temp_gradio_path = f"/tmp/output_{timestamp}.mp4"

        # Copy the video to the temp path
        shutil.copy(output_video_path, temp_gradio_path)

        # ✅ Show and autoplay video
        return gr.update(value=temp_gradio_path, visible=True, autoplay=True), ""



    except Exception as e:
        return f"❌ Error: {str(e)}"

# Gradio UI Setup
with gr.Blocks(title="DigiTwin") as demo:
    gr.Markdown("<h1 style='text-align: center;'>🧠 DigiTwin</h1>", elem_id="title")
    description_text = gr.Markdown("### Create your own Digital Twin by uploading your files below.")

    with gr.Row() as upload_row:
        doc_input = gr.File(label="📄 Upload PDF or Text File", file_types=[".pdf", ".txt"])
        audio_input = gr.Audio(label="🎵 Upload Audio File", type="filepath")
        image_input = gr.File(label="🖼️ Upload Image File", file_types=[".png", ".jpg", ".jpeg"])
        instruction_input = gr.Textbox(label="✍️ Instruction for Your Twin", placeholder="e.g. Speak like Sherlock Holmes...")

    submit_btn = gr.Button("🔍 Preview Uploads", visible=True)

    with gr.Row(visible=True) as preview_row:
        doc_preview = gr.Textbox(label="📄 Document Text Preview (First 1000 chars)", lines=6)
        audio_preview = gr.Textbox(label="🎵 Audio File Path")
        image_preview = gr.Image(label="🖼️ Uploaded Image Preview")
        instruction_preview = gr.Textbox(label="📝 Instruction (Saved)", interactive=False)


    clone_btn = gr.Button("✨ Create Clone", visible=True)
    clone_status = gr.Textbox(label="Clone Status", lines=2)

    gr.Markdown("### 💬 Ask your Clone")

    with gr.Row():
        with gr.Column(scale=1):
            query_input = gr.Textbox(label="Ask a Question")
            ask_btn = gr.Button("🧠 Ask")

        with gr.Column(scale=1):
            query_output = gr.Video(label="Response Video", format="mp4", visible=True)

    # Upload preview
    submit_btn.click(
        fn=handle_upload,
        inputs=[doc_input, audio_input, image_input, instruction_input],
        outputs=[doc_preview, audio_preview, image_preview, instruction_preview]
    )

    # Create clone and hide all the upload-related UI, and also hide the clone status after creation
    clone_btn.click(
        fn=create_clone_with_timeout,
        inputs=[doc_preview, audio_preview, image_preview],
        outputs=[clone_status]
    ).then(
        fn=lambda: (
            gr.update(visible=False),  # upload_row
            gr.update(visible=False),  # preview_row
            gr.update(visible=False),  # clone_btn
            gr.update(visible=False),  # submit_btn
            gr.update(visible=False),  # description_text
            gr.update(visible=False)   # clone_status (hide after creation)
        ),
        inputs=[],
        outputs=[upload_row, preview_row, clone_btn, submit_btn, description_text, clone_status]
    )

    # Ask with typed input
    ask_btn.click(
        fn=lambda x: "🕐 Generating response...",
        inputs=[query_input],
        outputs=[clone_status]
    ).then(
        fn=ask_clone_with_timeout,
        inputs=[query_input],
        outputs=[query_output, clone_status]
    )

demo.launch(share=True, debug=True, max_threads=1)





Colab notebook detected. This cell will run indefinitely so that you can see errors and logs. To turn off, set debug=False in launch().
* Running on public URL: https://a549bbe864fb2e7608.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)


🚀 Starting clone creation...
📝 Text preview:
Elon Musk
(00:00:49) Drinking coffee or water?

Elon Musk
(00:00:58) Sure.

Elon Musk
(00:01:02) This supposed to keep you up for like tomorrow afternoon, basically.

Elon Musk
(00:01:11) So what is Nitro? It’s just got a lot of caffeine or something?

Elon Musk
(00:01:17) It’s got nitrogen in it. That’s ridiculous. What we breathe is 78% nitrogen anyway. What do you need to add more for?

Elon Musk
(00:01:24) Unfortunately, you’re going to eat it.

Elon Musk
(00:01:29) Most people think that th
🔊 Audio path: /content/uploaded/uploaded_audio.wav
🖼️ Image path: [[[ 32  31  29]
  [ 31  30  28]
  [ 32  31  29]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[ 32  31  29]
  [ 31  30  28]
  [ 32  31  29]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[ 32  31  29]
  [ 31  30  28]
  [ 32  31  29]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[ 58  58  60]
  [ 58  58  60]
  [ 58  58  60]
  ...
  [255 255 255]



Loading files: 100%|██████████| 1/1 [00:00<00:00, 78.53file/s]


✅ Clone created!


/usr/local/lib/python3.11/dist-packages/transformers/generation/configuration_utils.py:631: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.7` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/transformers/generation/configuration_utils.py:636: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.


Response: I own Tesla, SpaceX, Neuralink, and X (formerly Twitter). I also have investments in SolarCity, The Boring Company, and OpenAI. I don't own any significant stakes in other companies.

--- Starting Voice Cloning ---
 > Reference: /content/uploaded/uploaded_audio.wav
 > Text: "I own Tesla, SpaceX, Neuralink, and X (formerly Twitter). I also have investments in SolarCity, The ..."
 > Language: en
 > Output: /content/generated/speech.wav
 > Text splitted to sentences.
['I own Tesla, SpaceX, Neuralink, and X (formerly Twitter).', 'I also have investments in SolarCity, The Boring Company, and OpenAI.', "I don't own any significant stakes in other companies."]
 > Processing time: 9.326565742492676
 > Real-time factor: 0.4592551332358852

Success! Generated in 9.40 seconds.
✅ Cloned speech saved to /content/generated/speech.wav
Job started with ID: e2e8a10e-3896-4792-bade-7dd358b13aca
Status: processing
Status: processing
Status: processing
Status: processing
Status: processing
Statu

/usr/local/lib/python3.11/dist-packages/transformers/generation/configuration_utils.py:631: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.7` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/transformers/generation/configuration_utils.py:636: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(


Response: I believe that President Trump displayed courage under fire during his presidency, especially after getting shot. Despite his flaws, I think he was a better choice than Biden at the time, given the need for a strong and courageous leader to deal with tough people and other world leaders. However, I'm not blind to his imperfections, and I'm not an unwavering supporter of all his decisions. I do think that reducing government spending and securing our borders are important issues. I've also discussed with Trump the idea of a government deficiency commission, which I'd be willing to be a part of. But I understand that my views on Trump are not universally accepted, and there are certainly

--- Starting Voice Cloning ---
 > Reference: /content/uploaded/uploaded_audio.wav
 > Text: "I believe that President Trump displayed courage under fire during his presidency, especially after ..."
 > Language: en
 > Output: /content/generated/speech.wav
 > Text splitted to sentences.
['I belie